#!/bin/bash

# Determine hostname
echo Hostname: `ssh -t root@$1 hostname`

# Determine domain account owner
echo Username: `ssh -t root@$1 /scripts/whoowns $1`

# Write home directory
echo Home directory: /home/`ssh -t root@$1 /scripts/whoowns $1`
